name: tests
on:
  push:
  pull_request:
  schedule:
  - cron: 0 6 * * MON,FRI
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: {}
    steps:
      - uses: actions/checkout@v3
      - run: test/run-container.sh

  cargo-deny:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
